version: '3.8'

services:
  db:
    image: postgres:15
    container_name: webz_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: webz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
